namespace guzFlightsUltra.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text;
    using Microsoft.AspNetCore.Identity;

    public class User //: IdentityUser
    {
        public User()
        {
            //this.UserRatedAlbums = new List<UserRatedAlbum>();
        }

        [Key]
        public int UserId { get; set; }

        public string UserName { get; set; }

        // password, generated by IdentityUser

        public string FirstName { get; set; }
        public string LastName { get; set; }

        //EGN
        public string SSN { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }

        //  !!!!!!! role, generated by IdentityUser

    }
}